### ISSUE TITLE
`GrpAbFinGen`: nonempty `gens(A)` for trivial `A`

### ISSUE THREAD

**Issue by ThomasBreuer** [thofma/Hecke.jl#1023]
Is the following intended?
```
julia> G = abelian_group(Int[]);  A, _ = sub(G, gens(G));

julia> gens(A)
1-element Vector{GrpAbFinGenElem}:
 Element of A with components [0]

julia> gens(G)
GrpAbFinGenElem[]
```

**Comment by thofma** [comment]
Probably not. I think at some point in the past, someone wanted to represent the trivial group as `Z/0`. But I think we went away from this idea. This might be an artifact of this.

**Comment by ThomasBreuer** [comment]
Thanks.
Having a redundant list of generators is not an error, but perhaps `is_snf(A)` should return `false`?
