### ISSUE TITLE
Block Banner output when using Hecke as dependency

### ISSUE THREAD

**Issue by iliailmer** [thofma/Hecke.jl#109]
Hi,

Is there a way to disable banner output from Hecke when `using` it as a dependency for a custom module?
Let me know if more details are required for this issue.

Thanks.

**Comment by thofma** [comment]
I added a banner which can be disabled by `HECKE_PRINT_BANNER=false` (will be available in the next version). I will close this issue here in favor of https://github.com/oscar-system/Oscar.jl/issues/92.
