### ISSUE TITLE
`saturate` fails for singular matrices

### ISSUE THREAD

**Issue by mgkurtz** [thofma/Hecke.jl#1101]
Saturating `ZZ[0 0;0 0]` should return (a copy of) the input, I think. It seems like the code for `saturate` manually computes the transform from `hnf_with_transform`. Perhaps, we could just use `hnf_with_transform` directly? I will try this in a PR.

**Comment by fieker** [comment]
On Thu, Jun 01, 2023 at 11:58:21PM -0700, Markus Kurtz wrote:
> Saturating `ZZ[0 0;0 0]` should return (a copy of) the input, I think. It seems like the code for `saturate` manually computes the transform from `hnf_with_transform`. Perhaps, we could just use `hnf_with_transform` directly? I will try this in a PR.

It does not T^-1 would always be a square matrix but the result is
usually not square. (it's boring in this case)

saturate as it currently is, requires full rank input which shoudl
possibly be mentioned/ enforced (this is equivalent to hnf in the code
being invertable)

julia> saturate(ZZ[2 2 2; 0 1 0])
[1   1   1]
[0   1   0]

julia> hnf_with_transform(ZZ[2 2 2; 0 1 0])
([2 0 2; 0 1 0], [1 -2; 0 1])

**Comment by thofma** [comment]
Fixed in #1102
