### ISSUE TITLE
factor of rational numbers : StackOverflowError 

### ISSUE THREAD

**Issue by WimKlim** [thofma/Hecke.jl#1110]
I get (Julia version v1.9.0 Windows 64-Bit, Hecke version 0.18.14) : 

julia> factor(12//35)
ERROR: StackOverflowError:
Stacktrace:
     [1] factor(a::Rational{Int64}; b::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
       @ Hecke xxx\.julia\packages\Hecke\ttSxw\src\Misc\Integer.jl:712
     [2] factor(a::Rational{Int64})
       @ Hecke xxx\.julia\packages\Hecke\ttSxw\src\Misc\Integer.jl:712
     [3] factor(x::Rational{Int64})
       @ Hecke xxx\.julia\packages\Hecke\ttSxw\src\Hecke.jl:239--- the last 3 lines are repeated 26660 more times ---

**Comment by WimKlim** [comment]
Thanks, factor(QQ(12//35), ZZ) works and is what I expect (ZZ (with negative exponents)) .
The Nemo version is 0.34.4 .

**Comment by fieker** [comment]
On Mon, Jun 05, 2023 at 06:26:08AM -0700, WimKlim wrote:
>  Thanks, factor(QQ(12//35), ZZ) works and is what I expect (ZZ (with negative exponents)) .
> The Nemo version is 0.34.4 .
> 
We're about the change the order of the arguments...

**Comment by thofma** [comment]
We are missing the `factor(x::Rational) = factor(QQ(x))` fallback and similar for the two-argument version.
