### ISSUE TITLE
Unexpected behaviour for pseudo-hnf

### ISSUE THREAD

**Issue by StevellM** [thofma/Hecke.jl#1112]
Here is one example from our test file `QuadForm/Lattices.jl`. I am currently working on the hashes for `QuadForm` and it turned out that while modifying the equality test for `AbstractLat`, the following test fails:
```
K, a = CyclotomicRealSubfield(8, "a");
Kt, t = K["t"];
E, b = number_field(t^2 - a * t + 1, "b");
V = hermitian_space(E, gram_matrix(root_lattice(:E, 8)));
L = lattice(V);
L2 = dual(L);
@test L == L2
```
In fact, this should be true. The modification for the equality test was changing the previous `_modules_equality` between the pseudo-hnf of the pseudo-bases of both lattices, to a regular equality `==`. Though here, if one computes the lower-left pseudo-hnf for L2 (choice made for the internal `_pseudo_hnf(::AbstractLat)`, we have the following
```
julia> pseudo_matrix(L2)
Pseudo-matrix over Relative maximal order of Relative number field of degree 2 over maximal real subfield of cyclotomic field of order 8
with pseudo-basis 
(1, 1//1 * <1, 1>)
(b, 1//1 * <1, 1>)
Fractional ideal with row [4 7 10 8 6 4 2 5]
Fractional ideal with row [7 14 20 16 12 8 4 10]
Fractional ideal with row [10 20 30 24 18 12 6 15]
Fractional ideal with row [8 16 24 20 15 10 5 12]
Fractional ideal with row [6 12 18 15 12 8 4 9]
Fractional ideal with row [4 8 12 10 8 6 3 6]
Fractional ideal with row [2 4 6 5 4 3 2 3]
Fractional ideal with row [5 10 15 12 9 6 3 8]

julia> pseudo_hnf(ans, :lowerleft)
Pseudo-matrix over Relative maximal order of Relative number field of degree 2 over maximal real subfield of cyclotomic field of order 8
with pseudo-basis 
(1, 1//1 * <1, 1>)
(b, 1//1 * <1, 1>)
Fractional ideal with row [1 0 0 0 0 0 0 0]
Fractional ideal with row [0 1 0 0 0 0 0 0]
Fractional ideal with row [0 0 1 0 0 0 0 0]
Fractional ideal with row [0 0 0 1 0 0 0 0]
Fractional ideal with row [0 0 0 0 1 0 0 0]
Fractional ideal with row [0 0 0 0 0 1 0 0]
Fractional ideal with row [0 0 0 0 0 0 1 0]
Fractional ideal with row [384 768 0 0 0 0 0 1]
```
However, this is not good enough... in fact, I can recall again `pseudo_hnf` on this last pseudo-matrix and
```
julia> pseudo_hnf(ans, :lowerleft)
Pseudo-matrix over Relative maximal order of Relative number field of degree 2 over maximal real subfield of cyclotomic field of order 8
with pseudo-basis 
(1, 1//1 * <1, 1>)
(b, 1//1 * <1, 1>)
Fractional ideal with row [1 0 0 0 0 0 0 0]
Fractional ideal with row [0 1 0 0 0 0 0 0]
Fractional ideal with row [0 0 1 0 0 0 0 0]
Fractional ideal with row [0 0 0 1 0 0 0 0]
Fractional ideal with row [0 0 0 0 1 0 0 0]
Fractional ideal with row [0 0 0 0 0 1 0 0]
Fractional ideal with row [0 0 0 0 0 0 1 0]
Fractional ideal with row [0 0 0 0 0 0 0 1]
```
This would be the one expected, since it is exactly the same pseudo-hnf for `L`, though by applying only once the function, we have a "non-totally reduced form". Thus, for Hecke, the equality does not hold. 

Note that `is_pseudo_hnf` returns true in both cases, so we have two non equal pseudo-hnf for the same pseudo-matrix, which we do not want.

**Comment by joschmitt** [comment]
I'll look into `pseudo_hnf`-thing.
(`L == L2` gives true for me though.)

**Comment by StevellM** [comment]
Thanks!
Yes in the current version of the equality for `AbstractLat`, it works. This has to be changed for hashing, and so we need to compare pseudo-hnf (which should be unique), and not only check whether they define the same module (which we currently do).
