### ISSUE TITLE
Quaternion algebra is commutative?

### ISSUE THREAD

**Issue by lgoettgens** [thofma/Hecke.jl#1139]
```julia
julia> A = Hecke.AlgQuat(QQ, QQ(-1), QQ(-1))
Quaternion algebra over
Rational field
defined by i^2 = -1, j^2 = -1

julia> A isa Ring
true

julia> _,i,j,k = basis(A);

julia> i*j == j*i
false
```
I think the inheritance from `Ring` is a mistake here, as that should only be the case for commutative rings, which is not the case here.

**Comment by thofma** [comment]
Once upon a time, matrices could only be constructed over `<: Ring`. I think this was changed some time ago, so we could fix it now.
