### ISSUE TITLE
Docstring misleading for `can_solve(::QuadBin, ::Int)`

### ISSUE THREAD

**Issue by lgoettgens** [thofma/Hecke.jl#1159]
See https://github.com/thofma/Hecke.jl/blob/351ca038b792548f46e4252f9d2289815ebbcac7/src/QuadForm/QuadBin.jl#L157-L163

The function name and docstring mismatch.
What of the two should be changed? I would say the function name (since the function returns a boolean an something else (maybe a solution? I am not familiar with quadratic forms)).

**Comment by StevellM** [comment]
Thanks, that is actually inconsistent. I will take care of that.

Here, the name of the function should be changed: the second output is in fact a solution to the equation `f(x,y) = n`.

**Comment by simonbrandhorst** [comment]
Resolved in #1163
