### ISSUE TITLE
`hermitian_structure_with_transfer_data` fails for isometry with infinite order

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#1210]
Maybe this is not meant to be supported; but there *is* some code in there which explicitly checks for infinity, but then at some point it runs into code that assumes the order to be finite...

Example to reproduce:
```
julia> L = integer_lattice(identity_matrix(ZZ,2); gram=ZZ[1 2; 2 1]);

julia> is_definite(L)
false

julia> gens = automorphism_group_generators(L);

julia> f = gens[1]
[4   -1]
[1    0]

julia> multiplicative_order(f)
infinity

julia> hermitian_structure_with_transfer_data(L, f)
ERROR: MethodError: no method matching euler_phi(::PosInf)
```

There error is in `src/QuadForm/Lattices.jl:1393`.

**Comment by thofma** [comment]
@StevellM Any idea?

**Comment by StevellM** [comment]
Yes looks like I modified the code to have it ready and available for infinite order but I forgot a part of the code in the process. I will fix this as soon as I have time for i.
