### ISSUE TITLE
Documentation redirecting from https to http

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#1300]
In various places we give <https://thofma.github.io/Hecke.jl/dev/> as URL for the documentation.

But this is currently a redirect to <http://www.thofma.com/Hecke.jl/dev/> which uses HTTP instead of HTTPs. I tested and HTTPS actually works there, so it's just a matter of fixing the redirect, I guess?

**Comment by thofma** [comment]
Should be working now. Could you retry?

**Comment by fingolfin** [comment]
Seems to be working now, thanks!
