### ISSUE TITLE
Names for group types

### ISSUE THREAD

**Issue by thofma** [thofma/Hecke.jl#1368]
I am writing down new names for the types related to groups: https://hackmd.io/ONVPdlfARgWzkfkNkcJkgA?both#Something-with-groups

I would appreciate some help with it @ThomasBreuer @fingolfin @fieker. I guess we can live with `FinGenGrpAb`? But what about the thing which is now called `GrpGen`, a group which is represented using a multiplication table. `GenericGroup` does not sound right. Maybe `CayleyTableGroup`? `MultiplicationTableGroup`?

**Comment by fingolfin** [comment]
I agree with all that @ThomasBreuer said, and would add that
- I'd stress the "if" in "if we want to keep the names" (I mean, I kinda do want to keep them, but of course they are not set in stone)
- ring types end with `...Ring` so I think group types should end with `...Group`
- we just changed a lot of ring morphism types to end with `...RingHom` so I wonder why  use `...GroupMor` and not `...GroupHom`?

**Comment by thofma** [comment]
- Are you planning to rename the group types? I have not been at all meetings and I can't find it in one of those HackMD documents.
- I must have missed that with the `RingHom`. Is the convention to use `...Hom` written down anywhere? (We will probably have `SchemeMor`, so I wonder why we would want to go for this mismatch.)

OK, so `FinGenAbGroup`, `FinGenAbGroupHom`, `MultTableGroup` and `...Hom` it is. Thanks!
