### ISSUE TITLE
Untangle different `factor` functions

### ISSUE THREAD

**Issue by lgoettgens** [thofma/Hecke.jl#1394]
There is `Hecke.factor` and `AbstractAlgebra/Nemo.factor`.
Both of them have the other one as a fallback, see:
https://github.com/thofma/Hecke.jl/blob/bb9dbe60f8c7da4eb4f490b5d8fdfdeb690c3eb5/src/Hecke.jl#L223
https://github.com/thofma/Hecke.jl/blob/f96fb3b2cca05bbbf7a9d579e9c615cc0baed302/src/Misc/Integer.jl#L179

This has the drawback that for types, where `factor` is not supported (e.g. `QQBarElem`), one gets a `StackOverflowError` instead of the expected `MethodError`.

Maybe related: https://github.com/thofma/Hecke.jl/issues/1110

**Comment by fieker** [comment]
Just be very careful.
 - the tangle also involves the weired interaction between root(s) of polynomials and factor
 - the key reason for introducing this "monstrosity" was integer factorisation: the Hecke version is much more powerful, in general, than Nemo(=flint)
 - several of this are related to imprecise type parameters, sometimes deliberate to not unneccessaryly exclude, and sometimes by exident.
 - support for the AA-Int and Rat types is scetchy - and never was our priority or interest

**Comment by fingolfin** [comment]
In triage it was just discussed whether moving the integer factorisation from Hecke to Nemo might help. At least @fieker and @thofma seemed to be OK with it.

**Comment by fingolfin** [comment]
As far as I can tell this was resolved by PR #1611 (which was merged indirectly via PR #1613).
