### ISSUE TITLE
Cannot find e.g. `quadratic_field` or `wildanger_field` when searching the Hecke manual

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#1498]
The functions `quadratic_field`, `wildanger_field` and more are defined on https://www.thofma.com/Hecke.jl/dev/manual/number_fields/fields but when one uses the search feature of the manual to search for `quadratic_field` or `wildanger_field` they are not found.

I suspect this was caused by PR #1441 / commit 15b74846a643f74dc524f0321ba78cbffb403882 which change the relevant `@docs` block to use `canonical=false`.

**Comment by thofma** [comment]
I should change the Oscar docs to use the new files (same files, but with proper hierachy) and then delete those here. This should make the `canonical = false` superfluous. Hopefully.

**Comment by lgoettgens** [comment]
As we had a breaking Hecke release in the meantime, removing the old files no longer breaks Oscar 1.0, so you only need a fix for Oscar master

**Comment by thofma** [comment]
Should be fixed with #1565
