### ISSUE TITLE
Problem during the installation

### ISSUE THREAD

**Issue by AlessandroBudroni** [thofma/Hecke.jl#15]
I have a problem during the installation. When I type

`Pkg.add("Hecke")`

I get the following error

`  CC   ../build/antic/get_nmod_poly.lo
get_nmod_poly.c:37:19: fatal error: flint.h: No such file or directory
 #include "flint.h"
                   ^
compilation terminated.
../Makefile.subdirs:60: recipe for target '../build/antic/get_nmod_poly.lo' failed
make[2]: *** [../build/antic/get_nmod_poly.lo] Error 1
make[2]: Leaving directory '/home/alessandro/.julia/v0.5/Hecke/deps/hecke/antic'
Makefile:120: recipe for target 'libhecke.so.0.0.0' failed
make[1]: *** [libhecke.so.0.0.0] Error 2
make[1]: Leaving directory '/home/alessandro/.julia/v0.5/Hecke/deps/hecke'
Makefile:140: recipe for target 'library' failed
make: *** [library] Error 2`

I have installed FLINT from http://www.flintlib.org/downloads.html but I still get the same error. I am working on a Dell xps 13 9360 running Ubuntu 17.04.
Any ideas on how to solve it?

**Comment by thofma** [comment]
Can you try a `Pkg.update(Nemo)` followed by a `Pkg.build("Hecke")`? Thanks.

**Comment by AlessandroBudroni** [comment]
It worked, thank you!
