### ISSUE TITLE
factor(PolyElem{nf_elem}) slow..

### ISSUE THREAD

**Issue by fieker** [thofma/Hecke.jl#152]
consider:
x^22 + 11264*x^21 + 108134400*x^20 + 582253281280*x^19 + 2643810068725760*x^18 + 6274789714415321088*x^17 + 10393103790020736581632*x^16 - 26964124627218324678246400*x^15 - 61113430392878016266187571200*x^14 - 213091256467749679196075458560000*x^13 + 659795291037497073621484487835648000*x^12 - 218715905250259965549160383884820480000*x^11 - 4691479368859726215309700317515643617280000*x^10 + 18763705130498258945783687744375729600593920000*x^9 - 27621622828761193673571225505441090503620689920000*x^8 - 2847327150033767189886543281086124743621638881280000*x^7 + 96615588727173557503360268281161873703549936525639680000*x^6 - 229835907220318672403717140991492550238864203055104000000000*x^5 + 308733648987598398195527756629686765531719284130473574400000000*x^4 - 259665702138139321625728949251881979040351910093995900928000000000*x^3 + 135845160848670688869014474010007121327144581305391801958400000000000*x^2 - 40944244103037831174890279502367127526949781124619826437816320000000000*x + 5497408998449834675230023541576565374247802780368536137105408000000000000

then trying to factor over the number field defined by this, the majoritiy of the time is in the norm computation. As Magma does this in <2.5 sec, we should be able to improve on the norm

**Comment by thofma** [comment]
How long does it take in Hecke?

**Comment by fieker** [comment]
On Fri, Feb 05, 2021 at 03:48:39AM -0800, thofma wrote:
> How long does it take in Hecke?

approx 10 sec, most in the norm
