### ISSUE TITLE
Add warning for outdated docs

### ISSUE THREAD

**Issue by lgoettgens** [thofma/Hecke.jl#1590]
See https://github.com/oscar-system/Oscar.jl/issues/3907 for details.
Since Hecke used some non-default design in the past for its docs, and is now using some Vitepress setup, the approach from https://github.com/oscar-system/Oscar.jl/issues/3907 that worked for all other packages mentioned there does not apply here. Nonetheless, it would be great to have something similar for the old Hecke docs as well. In particular, the Vitepress setup does not even mention any version number on the page itself (e.g. https://www.thofma.com/Hecke.jl/v0.31/) such that users can compare the version numbers themselves too realize they use an outdated docs version.

**Comment by thofma** [comment]
There is at least a version picker now.

**Comment by thofma** [comment]
Added, see https://docs.hecke.thofma.com/v0.35.4/.

**Comment by lgoettgens** [comment]
The hyperlink on the mentioned page is a 404.

And is it possible to do this retroactively to all old releases? This is what this issues was originally for

**Comment by thofma** [comment]
Ah, sorry, I meant it is working for https://docs.hecke.thofma.com/v0.35.5/. For all older releases (except 0.35.0 - 0.35.4) it should be also there.
