### ISSUE TITLE
Groups are not cached when created

### ISSUE THREAD

**Issue by royess** [thofma/Hecke.jl#1598]
It seems that groups are not cached when created. So if I create a same group twice, it will return two unequal objects.

```julia
julia> G = abelian_group(10)
Z/10

julia> G1 = abelian_group(10)
Z/10

julia> G == G1
false

julia> GG = small_group(10,1)
Generic group of order 10 with multiplication table

julia> GG1 = small_group(10,1)
Generic group of order 10 with multiplication table

julia> GG == GG1
false
```

I noticed that rings and fields are typically cached. Are there some specific reasons why we do not cache groups?

**Comment by fieker** [comment]
On Mon, Sep 09, 2024 at 10:25:13PM -0700, Rabqubit wrote:
> It seems that groups are not cached when created. So if I create a same group twice, it will return two unequal objects.
> 
> ```julia
> julia> G = abelian_group(10)
> Z/10
> 
> julia> G1 = abelian_group(10)
> Z/10
> 
> julia> G == G1
> false
> 
> julia> GG = small_group(10,1)
> Generic group of order 10 with multiplication table
> 
> julia> GG1 = small_group(10,1)
> Generic group of order 10 with multiplication table
> 
> julia> GG == GG1
> false
> ```
> 
> I noticed that rings and fields are typically cached. Are there some specific reasons why we do not cache groups? 
> 
For rings/ fields there is an argument that you can (and should!)
request caching to be turned off.
For groups, mainly, no-one ever wanted this. Also be careful of
unintended consequences: for all real quadratic field, the unit group,
as an abelian group is
abelian_group([2, 0])
Do you really want all those groups to be identical?
As a rule of thumbs: the caching is useful mainly for interactive
beginners. "All" internal code switches the caching off...

What is your application?

**Comment by fingolfin** [comment]
So I think the answer essentially is: this works as intended.
