### ISSUE TITLE
Fix doctesting on CI

### ISSUE THREAD

**Issue by lgoettgens** [thofma/Hecke.jl#1601]
It seems that doctests are not part of any CI job (at least I could not find it). If this would be available, https://github.com/thofma/Hecke.jl/issues/1600 would have already been caught in https://github.com/thofma/Hecke.jl/pull/1588.

**Comment by thofma** [comment]
They are always run on 1.10, see https://github.com/thofma/Hecke.jl/actions/runs/10788562712/job/29919609424#step:6:530. But it seems they do not report an error.

**Comment by thofma** [comment]
Fixed in #1602
