### ISSUE TITLE
Documentation style

### ISSUE THREAD

**Issue by ulthiel** [thofma/Hecke.jl#161]
The font in the documentation is tiny—too tiny. I checked with Safari, Firefox, Chrome.

Also, the documentation of "Abelian groups" is empty. 

Is there a particular reason for not using Documenter (like for AbstractAlgebra and Nemo)? Then everything would be in the same style. (Edit: Of course, you can use whatever you want, just saying. I think Documenter looks nicer and also fits the rest).

**Comment by albinahlback** [comment]
Hmm, I think it has a nice appeal. However, I do not like that both sides of the text has "table of contents" and that there is no delimiters between main text and the ToCs (tinting the sidebar would do it, I think).

**Comment by fieker** [comment]
It is using the "same" Documenter as Nemo/AA, but "choose" a different presentation style. Switching to the Nemo style would be easy, although my understanding is that Nemo was considering switching to the Hecke style...

**Comment by ulthiel** [comment]
But the font is too small, isn't it? Maybe it's macOS but at least I've tested Safari, Firefox, Chrome all with the same result.

**Comment by thofma** [comment]
We will make it larger. I don't have a macOS available, but to get one more data point: Is the Magma font large enough for you? (Both code and text).

**Comment by ulthiel** [comment]
You mean the Magma documentation? OK, it's quite small as well but at least a bit larger. The Github font size is perfect for example. (Am I sitting too far away from my display?!)

**Comment by thofma** [comment]
Thanks for checking. I will use the github font size. Sounds like a good idea.

**Comment by thofma** [comment]
Fixed.
