### ISSUE TITLE
"principal_subfields" not defined

### ISSUE THREAD

**Issue by ndrean** [thofma/Hecke.jl#1656]
julia version 1.11.1
Hecke Version 0.24.3 ... via Oscar Version 0.14.

```
julia> principal_subfields(L)
ERROR: UndefVarError: `principal_subfields` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] top-level scope

is_subfield_normal(K,L)
ERROR: UndefVarError: `is_subfield_normal` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
```

**Comment by thofma** [comment]
Out of curiosity, why did you expect those to exist? Are these functions used somewhere in the documentation or elsewhere?

**Comment by ndrean** [comment]
Because I found it here: <https://www.thofma.com/Hecke.jl/stable/manual/number_fields/fields>


[<img width="882" alt="Screenshot 2024-10-21 at 23 17 23" src="https://github.com/user-attachments/assets/a39d2063-6538-4c23-a062-6a37d30de394">](https://www.thofma.com/Hecke.jl/stable/manual/number_fields/fields)
<img width="903" alt="Screenshot 2024-10-21 at 23 18 11" src="https://github.com/user-attachments/assets/cd5becef-05d8-4834-9edd-de3e55f5c0b0">

**Comment by fieker** [comment]
On Mon, Oct 21, 2024 at 09:30:21AM -0700, Neven DREAN wrote:
> julia version 1.11.1
> Hecke Version 0.24.3 ... via Oscar Version 0.14.
> 
> ```
> julia> principal_subfields(L)
> ERROR: UndefVarError: `principal_subfields` not defined in `Main`
> Suggestion: check for spelling errors or missing imports.
> Stacktrace:
>  [1] top-level scope
> ```
> 
It's simply not exported:

Hecke.principal_subfields(L)

will work.

**Comment by ndrean** [comment]
Thanks. Works.

Although I don't understand why you responded this

> Out of curiosity, why did you expect those to exist?

**Comment by thofma** [comment]
Because I forgot that they are in the documentation.

**Comment by thofma** [comment]
Will be fixed in the next version. Thanks for your report.
