### ISSUE TITLE
Missing docstring and minor errors in documentation

### ISSUE THREAD

**Issue by albinahlback** [thofma/Hecke.jl#166]
Scrolling through the documentation for Hecke I saw some minor errors.

For example, at https://www.thofma.com/Hecke.jl/dev/orders/orders/ there is a missing docstring for `denominator` and a \Z at the first docstring (should probably be \mathbf{Z}).

**Comment by albinahlback** [comment]
Also the "Source" hyperref does not link anywhere. It opens a tab which contain a link under the name "None".

**Comment by albinahlback** [comment]
The long equation has a greater width than the text does. In some cases (but not the one shown here) it causes a cut-off at the end.
![Screenshot from 2021-02-18 00-51-40](https://user-images.githubusercontent.com/59514103/108283463-90dd2a80-7183-11eb-80d7-b3f642ff0bf2.png)

**Comment by albinahlback** [comment]
Missing docstring for maximal_order(::AnticNumberField, ::Array{fmpz, 1}).

**Comment by albinahlback** [comment]
There are some missing in docstrings in /Order, but I can't seem to find out why some of them behave that way. For example, I think `class_group` should be well-behaved, but it's missing.

**Comment by thofma** [comment]
Closing this in favor of other documentation issues.
