### ISSUE TITLE
Number field interface for the rationals

### ISSUE THREAD

**Issue by simonbrandhorst** [thofma/Hecke.jl#212]
`QQ` is a number field, so it could enjoy some of the number field interface 
For instance 
`maximal_order(QQ)` could return `ZZ` 
There could also be an ideal type for `ZZ`
and `infinite_places(QQ)` could work. 

My motivation is to make some generic code for quadratic forms over number fields also work for quadratic forms over `QQ`.

We need:

- [x] ideals (#212)
- [x] fractional ideals (#212)
- [x] places (#212)

**Comment by thofma** [comment]
Any opinion on this @fieker?

**Comment by fieker** [comment]
On Sun, Mar 14, 2021 at 07:46:03AM -0700, thofma wrote:
> Any opinion on this @fieker?
I'm happy for some functionality for QQ to be added. However, QQ is not
"just" a number field and that also has to be taken into account.

How far are you willing to go?
 - defining_equation
 - get/set coeff(raw)
 - conjugates/ completion
 - maximal_order (OK: trivial)
 - fractional ideals
 - class field theory (native implementation or hack?)
 - maps
 - ....

Maybe, for @simonbrandhorst 
 what do you envision to need?

(I think I just had the "same" discussion with s.o. else: should an
MPolyRing automatically be an MPolyQuoRing by the 0-ideal? Some things
will be easier, some impossible)

**Comment by simonbrandhorst** [comment]
Okay implementing the entire interface seems like a waste of time. If one wants all the functionality one has to work with something like `QQ[x]/(x-1)`. 
So I would stick to elementary things or to those things that someone actually needs.
- Ideals of `ZZ`
- `maximal_order(QQ)`
- the infinite place of `QQ`
Those I could use and they seem quite simple. 
The downside is that things remain incomplete / inconsistent.  
For instance one would expect that `ResidueRing(ZZ,Ideal(ZZ,2))` should work and probably dozens more. ... that might leave the user unsatisfied.

**Comment by fieker** [comment]
On Mon, Mar 15, 2021 at 03:27:44AM -0700, simonbrandhorst wrote:
> Okay implementing the entire interface seems like a waste of time. If one wants all the functionality one has to work with something like `QQ[x]/(x-1)`. 
> So I would stick to elementary things or to those things that someone actually needs.
> - Ideals of `ZZ`
> - `maximal_order(QQ)`
> - the infinite place of `QQ`
> Those I could use and they seem quite simple. 
> The downside is that things remain incomplete / inconsistent.  
> For instance one would expect that `ResidueRing(ZZ,Ideal(ZZ,2))` should work and probably dozens more. ... that might leave the user unsatisfied. 
> 

The next 10 HiWis or Fachpraktikanten or periods or boredom can add
things. As long as there is a findable list somewhere..

**Comment by thofma** [comment]
OK. I will add the types for ideals and fractional ideals soon and then we/someone can complete.
