### ISSUE TITLE
trail(PolyElem) vs trailing_coefficient

### ISSUE THREAD

**Issue by fieker** [thofma/Hecke.jl#24]
the 2nd is the constant term, the 1st the last non-zero. I think they are used wrongly.

**Comment by thofma** [comment]
Can't remember that I ever used them.

**Comment by thofma** [comment]
Did you fix it?

**Comment by fieker** [comment]
On Fri, Jan 05, 2018 at 07:08:19AM +0000, thofma wrote:
> Did you fix it?

Not yet - I am no sure. I'd like to delete trail from the existence,
however, It might have a use/meaning that I am not awre of...
