### ISSUE TITLE
Hecke changes `collect(::fmpz_mat)` to return a Vector instead of a Matrix

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#245]
If I just load AbstractAlgebra, I see this:
```
julia> M = MatrixSpace(ZZ, 2, 3); x = M(1:6); collect(x)
2×3 Matrix{BigInt}:
 1  2  3
 4  5  6
```
If I also load Nemo, I get this:
```
julia> M = MatrixSpace(ZZ, 2, 3); x = M(1:6); collect(x)
2×3 Matrix{fmpz}:
 1  2  3
 4  5  6
```
If I also load Hecke, I get this, which arguably is wrong:
```
julia> M = MatrixSpace(ZZ, 2, 3); x = M(1:6); collect(x)
6-element Vector{fmpz}:
 1
 4
 2
 5
 3
 6

```
This also happens if I force it to use AA.ZZ:
```
julia> M = MatrixSpace(AbstractAlgebra.ZZ, 2, 3); x = M(1:6); collect(x)
6-element Vector{BigInt}:
 1
 4
 2
 5
 3
 6
```

I noticed this because it breaks the doctests in the "new" Oscar.jl manual, which includes the AbstractAlgebra manual, which contains the above example.

**Comment by thofma** [comment]
Why wrong? It is incompatible since the other packages started implementing something different. We will fix it.

**Comment by fingolfin** [comment]
Well it's wrong in that it changes existing behavior, I think this is referred to as "type piracy". 

Also, the behavior before Hecke is loaded is consistent with how Julia matrices are treated by collect:
```
julia> m2 = [1 2 3 ; 4 5 6 ]
2×3 Matrix{Int64}:
 1  2  3
 4  5  6

julia> collect(m2)
2×3 Matrix{Int64}:
 1  2  3
 4  5  6
```

That said, I don't care so much how it behaves in the end, as long as it doesn't change depending in which packages are loaded.

**Comment by fieker** [comment]
Historic...
we implemented it in Hecke following the old julia way of, as far as I
can recall returning a one-dim vector.
Then julia changed and s.o. added it to AA in the new way.
As there was never any serious upwards testing...

**Comment by fieker** [comment]
On Tue, Mar 30, 2021 at 12:53:12AM -0700, Max Horn wrote:
> Well it's wrong in that it changes existing behavior, I think this is referred to as "type piracy". 
Can't be type piracy: fmpz_mat is our type.
Furthermore: it was defined in Hecke first and then added to AA - don't
know how this is called...
I'm happy to change this - provided the code will still run.
I personaly do not like the current juli behaviour as it requires all
functions to use the current multi-dim iterator interface.

**Comment by fingolfin** [comment]
OK, makes sense that this has historical reasons. I expected that it either had good reasons, or was an accident (I didn't see an "collect" method in Hecke, so I assume it's an indirect effect? As I learned just now, I guess `IteratorSize` has to be set to HasShape but is redefined, or so?)

I also do not mean to "blame" anybody, so I kinda regret even mentioning "type piracy" because the word "piracy" sounds so extremely negative, even though I meant it in a purely technical way (though it's even less clear to me now what this is supposed to mean -- I thought it simply refers to  redefining a method for a given tuple of input types previously defined in a dependency. Apparently people disagree, so combined with the negative association with "piracy", perhaps it's best to avoid this term).

But fact is that behavior changes depending on which packages are loaded, and that's bad, I am sure we agree on that. So, as I said, I am fine either way, as long as it is consistent across our package.

I would mildly prefer to follow what Julia does here, whether we like it or not, as I think this will make our lives and that of our users a bit easier on the long run; but that's of course just speculation. I suggest that if we want/need a function that always returns a vector, we should define it. And yeah, of course we need to be careful to not break our existing code in the meantime. Alternatively, if we keep the behavior as it is in Hecke (and thus change AA/Nemo/...), then IMHO we ought to explicitly document the divergent behavior and why we chose it.

**Comment by fingolfin** [comment]
OK, I just learned that one can write `reshape(collect(mat), :)` to always get a vector. Not saying this is great, but it's not that bad either.

**Comment by thofma** [comment]
`vec(collect(mat))` is even shorter.

**Comment by fieker** [comment]
On Tue, Mar 30, 2021 at 02:10:41AM -0700, Max Horn wrote:
> OK, I just learned that one can write `reshape(collect(mat), :)` to always get a vector. Not saying this is great, but it's not that bad either.
> 
reshape is not supported by us in Nemo matrices (and cannot). Hence:

    reshape(A, dims...) -> AbstractArray
    reshape(A, dims) -> AbstractArray

Return an array with the same data as `A`, but with different
dimension sizes or number of dimensions. The two arrays share the same
underlying data, so that the result is mutable if and only if `A` is
mutable, and setting elements of one alters the values of the other.

is not true in our case. It would copy...I think and thus need to be
avoided.

However, the problem is/was I thik not having implements hasshape or
similar originally. Don't know if it was even documented (this was done
in/ for 0.5)

**Comment by fieker** [comment]
By magic, aparently
  collect(m)
  vec(collect(m))
  reshape(collect(m), :)

all have exatly the same number of allocations and the same amount of
memory allocated...
In all cases it appears that the matrix entries are copied twice.
