### ISSUE TITLE
Maximal order failing for non-nice polynomials

### ISSUE THREAD

**Issue by thofma** [thofma/Hecke.jl#249]
```julia
julia> Qx, x = PolynomialRing(FlintQQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> f = 1//6*x^4 - 1//2*x^3 - x^2 + x + 5//2
1//6*x^4 - 1//2*x^3 - x^2 + x + 5//2

julia> K, a = number_field(f, cached = false)
(Number field over Rational Field with defining polynomial 1//6*x^4 - 1//2*x^3 - x^2 + x + 5//2, _a)

julia> Hecke.assertions(true)

julia> maximal_order(K)
ERROR: AssertionError: $(Expr(:escape, :(det(trace_matrix(OK)) == OK.disc)))
Stacktrace:
  [1] macro expansion
    @ ~/.julia/dev/Hecke/src/Assertions.jl:214 [inlined]
  [2] sum_as_Z_modules_fast(O1::NfOrd, O2::NfOrd, z::fmpz_mat)
    @ Hecke ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1270
  [3] sum_as_Z_modules_fast(O1::NfOrd, O2::NfOrd)
    @ Hecke ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1247
  [4] +(a::NfOrd, b::NfOrd; cached::Bool)
    @ Hecke ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1226
  [5] +
    @ ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1223 [inlined]
  [6] pmaximal_overorder_at(O::NfOrd, primes::Vector{fmpz})
    @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:123
  [7] new_maximal_order(O::NfOrd; index_divisors::Vector{fmpz}, disc::fmpz, ramified_primes::Vector{fmpz})
    @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:227
  [8] MaximalOrder(K::AnticNumberField; discriminant::fmpz, ramified_primes::Vector{fmpz})
    @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:73
  [9] MaximalOrder(K::AnticNumberField)
    @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:67
 [10] top-level scope
    @ REPL[43]:1
```

**Comment by fieker** [comment]
On Thu, Apr 01, 2021 at 03:51:14AM -0700, thofma wrote:
> ```julia
> julia> Qx, x = PolynomialRing(FlintQQ, "x")
> (Univariate Polynomial Ring in x over Rational Field, x)
> 
> julia> f = 1//6*x^4 - 1//2*x^3 - x^2 + x + 5//2
> 1//6*x^4 - 1//2*x^3 - x^2 + x + 5//2
> 
> julia> K, a = number_field(f, cached = false)
> (Number field over Rational Field with defining polynomial 1//6*x^4 - 1//2*x^3 - x^2 + x + 5//2, _a)
> 
> julia> Hecke.assertions(true)
> 
> julia> maximal_order(K)
> ERROR: AssertionError: $(Expr(:escape, :(det(trace_matrix(OK)) == OK.disc)))
> Stacktrace:
>   [1] macro expansion
>     @ ~/.julia/dev/Hecke/src/Assertions.jl:214 [inlined]
>   [2] sum_as_Z_modules_fast(O1::NfOrd, O2::NfOrd, z::fmpz_mat)
>     @ Hecke ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1270
>   [3] sum_as_Z_modules_fast(O1::NfOrd, O2::NfOrd)
>     @ Hecke ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1247
>   [4] +(a::NfOrd, b::NfOrd; cached::Bool)
>     @ Hecke ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1226
>   [5] +
>     @ ~/.julia/dev/Hecke/src/NfOrd/NfOrd.jl:1223 [inlined]
>   [6] pmaximal_overorder_at(O::NfOrd, primes::Vector{fmpz})
>     @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:123
>   [7] new_maximal_order(O::NfOrd; index_divisors::Vector{fmpz}, disc::fmpz, ramified_primes::Vector{fmpz})
>     @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:227
>   [8] MaximalOrder(K::AnticNumberField; discriminant::fmpz, ramified_primes::Vector{fmpz})
>     @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:73
>   [9] MaximalOrder(K::AnticNumberField)
>     @ Hecke ~/.julia/dev/Hecke/src/NfOrd/MaxOrd/MaxOrd.jl:67
>  [10] top-level scope
>     @ REPL[43]:1
> ```
> 
fixed in https://github.com/thofma/Hecke.jl/pull/252
