### ISSUE TITLE
Simplify failing for non-nice defining polynomial

### ISSUE THREAD

**Issue by thofma** [thofma/Hecke.jl#250]
```julia
julia> Qx, x = PolynomialRing(FlintQQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> f = -1//3*x^2 - x + 1
-1//3*x^2 - x + 1

julia> K, a = number_field(f, cached = false)
(Number field over Rational Field with defining polynomial -1//3*x^2 - x + 1, _a)

julia> simplify(K)
ERROR: ArgumentError: Not an exact division
Stacktrace:
 [1] divexact(x::fmpz, y::fmpz)
   @ Nemo ~/.julia/packages/Nemo/xNg6C/src/flint/fmpz.jl:366
 [2] simplify(K::AnticNumberField; canonical::Bool, cached::Bool, save_LLL_basis::Bool)
   @ Hecke ~/.julia/dev/Hecke/src/NumField/NfAbs/Simplify.jl:86
 [3] simplify(K::AnticNumberField)
   @ Hecke ~/.julia/dev/Hecke/src/NumField/NfAbs/Simplify.jl:19
 [4] top-level scope
   @ REPL[54]:1
```

**Comment by fieker** [comment]
On Thu, Apr 01, 2021 at 03:56:34AM -0700, thofma wrote:
> ```julia
> julia> Qx, x = PolynomialRing(FlintQQ, "x")
> (Univariate Polynomial Ring in x over Rational Field, x)
> 
> julia> f = -1//3*x^2 - x + 1
> -1//3*x^2 - x + 1
> 
> julia> K, a = number_field(f, cached = false)
> (Number field over Rational Field with defining polynomial -1//3*x^2 - x + 1, _a)
> 
> julia> simplify(K)
> ERROR: ArgumentError: Not an exact division
> Stacktrace:
>  [1] divexact(x::fmpz, y::fmpz)
>    @ Nemo ~/.julia/packages/Nemo/xNg6C/src/flint/fmpz.jl:366
>  [2] simplify(K::AnticNumberField; canonical::Bool, cached::Bool, save_LLL_basis::Bool)
>    @ Hecke ~/.julia/dev/Hecke/src/NumField/NfAbs/Simplify.jl:86
>  [3] simplify(K::AnticNumberField)
>    @ Hecke ~/.julia/dev/Hecke/src/NumField/NfAbs/Simplify.jl:19
>  [4] top-level scope
>    @ REPL[54]:1
> ```
> 
fixed in https://github.com/thofma/Hecke.jl/pull/252
