### ISSUE TITLE
`issquare` giving wrong results

### ISSUE THREAD

**Issue by thofma** [thofma/Hecke.jl#251]
```julia
julia> Qx, x = PolynomialRing(FlintQQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> K, a = number_field(f, cached = false)
(Number field over Rational Field with defining polynomial -6//7*x + 1//9, 7//54)

julia> c = 49//4
49//4

julia> issquare(K(c))
(false, 0)
```
@fieker

**Comment by fieker** [comment]
On Thu, Apr 01, 2021 at 04:05:46AM -0700, thofma wrote:
> ```julia
> julia> Qx, x = PolynomialRing(FlintQQ, "x")
> (Univariate Polynomial Ring in x over Rational Field, x)
> 
> julia> K, a = number_field(f, cached = false)
> (Number field over Rational Field with defining polynomial -6//7*x + 1//9, 7//54)
> 
> julia> c = 49//4
> 49//4
> 
> julia> issquare(K(c))
> (false, 0)
> ```
> @fieker 

fixed in https://github.com/thofma/Hecke.jl/pull/252
