### ISSUE TITLE
Identities, zero matrices, concatenations for sparse matrices

### ISSUE THREAD

**Issue by sebastianpos** [thofma/Hecke.jl#26]
It would be nice to have constructors for
- identities
- zero matrices

that return sparse matrices.
Moreover, it would also be nice to have basic
concatenation methods for sparse matrices, like
- vcat
- hcat
- cat( (1,2), ...)

**Comment by thofma** [comment]
Can you elaborate on `cat( (1,2), ...)`?

**Comment by sebastianpos** [comment]
`cat ( (1,2), A,B,C,... )`
should create a diagonal matrix having
the matrices A,B,C,... on its diagonal.

**Comment by thofma** [comment]
OK. Final question: What is the `(1, 2)` supposed to indicate?

**Comment by fingolfin** [comment]
There is `zero_matrix(SMat, QQ, nrows, ncols)` as well as `vcat` and `hcat` methods. There is no `cat(A...; dims)` support but there is `block_diagonal_matrix`.

So can this be closed?
