### ISSUE TITLE
problems with `force_coerce_cyclo`

### ISSUE THREAD

**Issue by ThomasBreuer** [thofma/Hecke.jl#307]
The following examples look irritating.
(It is not clear which of them are wrong because the precise meanings of the functions are not documented.)
```julia
julia> function cyclo_expl(n, m)
       Fn, zn = Nemo.CyclotomicField(n)
       Fnm, znm = Nemo.CyclotomicField(n*m)
       x = zn
       x_up = Hecke.force_coerce_cyclo(Fnm, x)
       x_down = Hecke.force_coerce_cyclo(Fn, x_up)
       return (x, x_up, x_down)
       end;

julia> res = cyclo_expl(3, 4)
(z_3, z_12^2, z_3)

```
Here I would say we have a bug: Coercing a 3rd root of unity to the 12th cyclotomic field yields a primitive 6th root of unity.
```julia
julia> res[1]^3, res[2]^3
(1, -1)

```
The next result can be regarded as correct, although it means that the generators of the cyclotomic fields cannot be thought of as the complex values $\exp(2*\pi i/n)$. (If `z_3` would be coerced to `z_6^2` then this interpretation would be possible.)
```julia
julia> res = cyclo_expl(3, 2)
(z_3, -z_6, z_3)

```
For two even conductors, there is no such problem.
```julia
julia> res = cyclo_expl(6, 2)
(z_6, z_12^2, z_6)

```
If we agree that the current behaviour is not correct, we can change the definitions, and document them.
My proposal would then be that the generator `z_n` of the `n`-th cyclotomic field should be coerced to `z_N^(N/n)` in the `N`-th cyclotomic field whenever `n` divides `N`. This way, coercion between cyclotomic fields is automatically consistent.

**Comment by thofma** [comment]
Thanks Thomas. @fieker
