### ISSUE TITLE
`to_univariate` broken

### ISSUE THREAD

**Issue by 8d1h** [thofma/Hecke.jl#317]
Hi! The function `to_univariate` is broken (in Oscar too), since the function `isunivariate` is redefined and returns not just a boolean but a tuple. Maybe we could just redefine `to_univariate` too to make it return `isunivariate(f)[2]`?
```julia
julia> R, x = PolynomialRing(QQ, ["x"])
(Multivariate Polynomial Ring in x over Rational Field, fmpq_mpoly[x])

julia> isunivariate(x[1])
(true, x)

julia> to_univariate(QQ["x"][1], x[1])
ERROR: MethodError: no method matching !(::Tuple{Bool, fmpq_poly})
```

**Comment by thofma** [comment]
Thanks. I plan to untangle this soon.

**Comment by thofma** [comment]
Fixed.
