### ISSUE TITLE
MethodError: AbstractAlgebra.Generic.change_base_ring(::fmpq_poly, ::AnticNumberField) is ambiguous

### ISSUE THREAD

**Issue by heiderich** [thofma/Hecke.jl#36]
There is a problem with `change_base_ring`:

```
Change of ring: Error During Test at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/test/AlgAss/AlgAss.jl:65
  Test threw exception
  Expression: (isisomorphic(K, base_ring(C)))[1]
  MethodError: AbstractAlgebra.Generic.change_base_ring(::fmpq_poly, ::AnticNumberField) is ambiguous. Candidates:
    change_base_ring(f::PolyElem, R::AbstractAlgebra.Ring) in Hecke at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/src/Misc/Poly.jl:548
    change_base_ring(p::PolyElem{T}, g) where T<:Union{RingElem, AbstractFloat, Integer, Rational} in AbstractAlgebra at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/AbstractAlgebra/Ot2xj/src/Rings.jl:248
  Possible fix, define
    change_base_ring(::PolyElem{T<:Union{RingElem, AbstractFloat, Integer, Rational}}, ::AbstractAlgebra.Ring)
  Stacktrace:
   [1] #roots#923(::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:max_roots,),Tuple{Int64}}}, ::Function, ::fmpq_poly, ::AnticNumberField) at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/src/NfAbs/Elem.jl:579
   [2] (::getfield(Nemo, Symbol("#kw##roots")))(::NamedTuple{(:max_roots,),Tuple{Int64}}, ::typeof(roots), ::fmpq_poly, ::AnticNumberField) at ./none:0
   [3] _issubfield(::AnticNumberField, ::AnticNumberField) at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/src/NfAbs/NfAbs.jl:407
   [4] isisomorphic(::AnticNumberField, ::AnticNumberField) at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/src/NfAbs/NfAbs.jl:536
   [5] top-level scope at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/test/AlgAss/AlgAss.jl:65
   [6] top-level scope at /var/jenkins_home/workspace/oscar/julia/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [7] top-level scope at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/test/AlgAss/AlgAss.jl:52
   [8] top-level scope at /var/jenkins_home/workspace/oscar/julia/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083
   [9] top-level scope at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/Hecke/f614M/test/AlgAss/AlgAss.jl:49
```

I think the problem is that the definition of

    change_base_ring(p::PolyElem{T}, g) where T<:Union{RingElem, AbstractFloat, Integer, Rational} in AbstractAlgebra at /var/jenkins_home/workspace/oscar/jenv/pkg/packages/AbstractAlgebra/Ot2xj/src/Rings.jl:248

is too general. I am going to provide a pull request to change its signature.

**Comment by thofma** [comment]
No, no need to change the signature. I just did not have time to adjust to the recent changes in AbstractAlgebra.

**Comment by heiderich** [comment]
But I think it would anyway be good to specify the type of `g` in the signature, so that users know what to pass. I thought about using `Function` for `g`. And to be clear: I am proposing to change the signatures of the `change_base_ring` functions in AbstractAlgebra, not the one in Hecke.

**Comment by thofma** [comment]
Function is too restrictive, since we also just want to pass the ring. There is not argument type which allows anything that is callable.

**Comment by heiderich** [comment]
I think I explained several times in the past why "we also just want to pass the ring" is problematic and I do not want to repeat it once more.

People started to use `change_base_ring` in such a way already:

https://github.com/Nemocas/AbstractAlgebra.jl/blob/8f838db7097ea7dafcacd1cd85c25774e63f5a1d/test/generic/Poly-test.jl#L2661-L2663

As I explained in the past, `g` should be a ring morphism. It is mathematically not clear what should happen when passing a ring.

What do you mean by "anything that is callable"?

**Comment by thofma** [comment]
It is clear from the definition that `change_base_ring(f, g)` applies `g` to the coefficients of `f`.  Here "applies" means just doing `g(a)`. In this sense `g` can be anything that is callable. Maybe I just want to square all the coefficients of `f`, so I will do `change_base_ring(f, x -> x^2)`. The name is maybe misleading, but so is it if you restrict it to morphisms.

**Comment by thofma** [comment]
Clear from the docstring, not definition, sorry.

**Comment by fieker** [comment]
On Thu, Jul 04, 2019 at 06:30:23AM -0700, Florian Heiderich wrote:
> I think I explained several times in the past why "we also just want to pass the ring" is problematic and I do not want to repeat it once more.
> 
> People started to use `change_base_ring` in such a way already:
> 
> https://github.com/Nemocas/AbstractAlgebra.jl/blob/8f838db7097ea7dafcacd1cd85c25774e63f5a1d/test/generic/Poly-test.jl#L2661-L2663
> 
> As I explained in the past, `g` should be a ring morphism. It is mathematically not clear what should happen when passing a ring.

It is clear by julia

change_base_ring(f, R) := change_base_ring(f, x->R(x))

what exactly happens in R(x): different question.
> 
> What do you mean by "anything that is callable"?
you can do R(x) "call" R as a "function

**Comment by thofma** [comment]
I just pushed a fix. This will be fixed in the next release which will happen today or tomorrow.

**Comment by heiderich** [comment]
> The name is maybe misleading, but so is it if you restrict it to morphisms.

Which name do you mean? `change_base_ring`? The mathematical concept I had in mind when defining this function for the first time was the universal property of polynomial rings applied in the special case of a polynomial ring in the same number of variables with the variables mapped to the "same" variables in the target polynomial ring. Here is a reference to the discussion we had back then:

https://github.com/Nemocas/AbstractAlgebra.jl/issues/106

> Maybe I just want to square all the coefficients of f, so I will do change_base_ring(f, x -> x^2).

The example you provide fits `Function`:
`isa(x -> x^2, Function)`

> It is clear by julia
> 
> change_base_ring(f, R) := change_base_ring(f, x->R(x))

This works if the the type of `R` in the signature is `Any` (as it is currently), not if it is `Function` (as I am suggesting it to be).

> what exactly happens in R(x): different question.

This is an important question. If people people decide to do this in their personal code this is fine. But I think we should discourage this in the library. Having to write `x -> R(x)` instead of `R` is reasonable in my opinion. And hopefully it will make people think about what to expect when writing `R(x)`.

> you can do R(x) "call" R as a "function

In general there is no canonical choice on how to coerce `x` into `R`, i.e. what `R(x)` should be. So I would discourage to allow "applying" rings to ring elements. What can be "applied" to ring elements are ring homomorphisms (or in general functions). I consider this important. When people what to think of a ring `R` as a function that can take ring elements `x` as an argument, I think they should make it formally a function by writing `x -> R(x)` just as you did above. When we encourage people to write `R` instead, `R(x)` might actually be implemented somewhere, but might not be what they have in mind.

**Comment by heiderich** [comment]
> I just pushed a fix. This will be fixed in the next release which will happen today or tomorrow.

I do not see anything. Which commit contains your fix?

**Comment by fieker** [comment]
On Thu, Jul 04, 2019 at 07:34:34AM -0700, Florian Heiderich wrote:
> > The name is maybe misleading, but so is it if you restrict it to morphisms.
> 
> Which name do you mean? `change_base_ring`? The mathematical concept I had in mind when defining this function for the first time was the universal property of polynomial rings applied in the special case of a polynomial ring in the same number of variables with the variables mapped to the "same" variables in the target polynomial ring. Here is a reference to the discussion we had back then:
> 
> https://github.com/Nemocas/AbstractAlgebra.jl/issues/106
> 
> > Maybe I just want to square all the coefficients of f, so I will do change_base_ring(f, x -> x^2).
> 
> The example you provide fits `Function`:
> `isa(x -> x^2, Function)`
> 
> > It is clear by julia
> > 
> > change_base_ring(f, R) := change_base_ring(f, x->R(x))
> 
> This works if the the type of `R` in the signature is `Any` (as it is currently), not if it is `Function` (as I am suggesting it to be).
> 
> > what exactly happens in R(x): different question.
> 
> This is an important question. If people people decide to do this in their personal code this is fine. But I think we should discourage this in the library. Having to write `x -> R(x)` instead of `R` is reasonable in my opinion. And hopefully it will make people think about what to expect when writing `R(x)`.
> 
> > you can do R(x) "call" R as a "function
> 
> In general there is no canonical choice on how to coerce `x` into `R`, i.e. what `R(x)` should be. So I would discourage to allow "applying" rings to ring elements. What can be "applied" to ring elements are ring homomorphisms (or in general functions). I consider this important. When people what to think of a ring `R` as a function that can take ring elements `x` as an argument, I think they should make it formally a function by writing `x -> R(x)` just as you did above. When we encourage people to write `R` instead, `R(x)` might actually be implemented somewhere, but might not be what they have in mind.

This is windows dressing, you're mathematically right of course, but the
point is: how do you indent to create interesting elements in R?
How do you specify the natural morphism Z -> R if R is unitary (to allow
integers to interact with R)

How do you create elements in Z/nZ, number fields (as different type,
not residue rings)?

That's why we decided to allow R(...) to create ring elements. It
"should" allow the "natural" and "obvious" data to be used to define
elements. We deliberately did not allow complicated, ambiguos stuff
here, but the ability to do this is at the foundations of any
recursively generated ring:

Q[s]

in order to implement generic polynomial rings, I need to be able to
create elements (polynomials) from scalars, eg 1+s does this: 1 is an
Int, but it can be coerced into Q using Q(1) and then it can be added to
s

You can object to R(x), but all that would (have to) happen is to have
element(R, x) (or object(R, x)) which has exactly the same problems/ 
functionality.

Think of R(x) as R!x in Magma. And yes, if you allow too much for x, it
becomes difficult. If you're too restrictive, the system is unusable.

Btw maps are also NOT functions, but simply callable objects...
Do oy also want to use change_base_ring(f, x->phi(x)) where phi is a
morphism? That would feel a bit silly...

**Comment by thofma** [comment]
The last commit https://github.com/thofma/Hecke.jl/commit/8842d375ae5897f90209abd9f410725fac4748af contains the fix, but I am also waiting for https://github.com/JuliaRegistries/General/pull/1784 to be merged.

**Comment by heiderich** [comment]
> The last commit [8842d37](https://github.com/thofma/Hecke.jl/commit/8842d375ae5897f90209abd9f410725fac4748af) contains the fix, but I am also waiting for [JuliaRegistries/General#1784](https://github.com/JuliaRegistries/General/pull/1784) to be merged.

@thofma In that commit you mostly comment out the `change_base_ring` functions. Does this really solve the problem? Are they not needed anymore?

@fieker I think we should distinguish between two questions here:
a) Should one have the `R(x)` syntax?
b) What type should the argument `g` of the `change_base_ring` function have?


Concerning a) I agree with you that this might be convenient in cases such as the ones you mentioned. I am not absolutely against this notation.

Concerning b) I initially proposed a new type for ring homomorphisms (https://github.com/Nemocas/AbstractAlgebra.jl/issues/106#issuecomment-399395006). This was not wanted (https://github.com/Nemocas/AbstractAlgebra.jl/issues/106#issuecomment-399401589). Now it seems that `Function` in not good enough for `g` because of the Map types in AbstanctAlgebra. I do not know them well enough, but I proposed a new type in https://github.com/Nemocas/AbstractAlgebra.jl/pull/350#issuecomment-508534930. 

> Btw maps are also NOT functions, but simply callable objects... Do oy also want to use change_base_ring(f, x->phi(x)) where phi is a morphism? That would feel a bit silly...

I agree with you that this would be silly. Would a new type such as proposed in https://github.com/Nemocas/AbstractAlgebra.jl/pull/350#issuecomment-508534930 address this issue?

I still think that allowing `g` to be a ring in `change_base_ring` is a bad idea.

**Comment by thofma** [comment]
Yes, this will fix it. We moved the function from Hecke to AbstractAlgebra.

We should continue the discussion in the AbstractAlgebra repository.

I am sympathetic to your idea of restricting things to proper morphisms, but I am afraid this is not possible with the properties/limitations of the julia type system.

**Comment by fieker** [comment]
OK: we've tried this, years ago, in Magma: restrict to only allow
certified homomorphisms in this situation.
Result: does not work.
 either one has to define way too many new types
 or deal with partial maps
 or both.

Point(s) in case:
  Q -> F_p x -> x mod p
is only well defined from Z -> F_p
can be extended from Z_(p) -> F_p while maintaining most features
However, Q -> Z_(p) does not work, so to make it mathematically sound I'd
have to
 - try to compute pointwise preimage (to invert Z_(p) -> Q) followed by
 - the projection to F_p
 - I'd also have to implement Z_(p), the map Z_(p) -> Q, the inverse and
   the projection

Since this is an important primitive building block for basically any
modular algorithm, this is not feasible.

Similar problem exists elsewhere: to insist on mathematical rigour
everywhere means inventing many new types (and to support them).

So instead we allow the use of partial-multi-maps.
If the map is a homomorphism, then mathematics guarantees all is fine.
If the map is only used where it is a homomorphism, all is fine.
If a user does s.th. absolutely silly, I cannot help.

Given a function (in the sense of Julia) I cannot hope to verify any
properties, let alone being a morphism or not. 

Julia allows objects to be callable - which we want for polynomial
evaluation and maps. But doing geometry, also for evaluating elements at
places....
There is nothing intrinsically special about functions... other than
having a supertype.
