### ISSUE TITLE
can_solve_with_kernel returns incorrect results

### ISSUE THREAD

**Issue by wbhart** [thofma/Hecke.jl#377]
In the ring case the final return value is essentially always incorrect, though I have managed to fix that in the version I am implementing for AbstractAlgebra.

However the field case frequently returns the incorrect kernel. Here is a specific example:

```
using Hecke
M = matrix(QQ, 2, 9, [37//19 4167//8 632//9 127//2 6268//95 -2487//13 -117//190 6793//380 -1231//3; 9//19 507//4 154//9 31//2 1526//95 -605//13 -29//190 1661//380 -100])
B = matrix(QQ, 2, 9, [36509513279//19710600 -333707923//556920 -12611630942//2463825 2052298517//3260400 135240137//889200 -468468844939//290990700 -235276429//125400 306806125153//28721160 416877067//518700; 17762102161//39421200 -192846298//1322685 -36830950333//29565900 1501627327//9781200 1828703//49400 -2595021407//6613425 -216977//475 2075621461//797810 76147888//389025])
flag, S, K = can_solve_with_kernel(M, B)
```

The resulting kernel is not correct.

Any hints as to why this might be would be helpful.

**Comment by thofma** [comment]
I am actually not sure one can read of the kernel of a matrix from its echelon form. Surely one can get the kernel of the echelon form, but there is still a transformation missing. What do you think @fieker?

P.S.: `M = matrix(QQ, 3, 3, [0, -2, -2, -1, 1, -2, 1, -1, 2])` with arbitrary right hand side will also fail.

**Comment by wbhart** [comment]
I think it should be possible, as this is over a field. Note A and B are concatenated together before the rref is taken. Having said that, I don't understand what is happening in the second half of this.
