### ISSUE TITLE
maximial order computation does not work

### ISSUE THREAD

**Issue by martinra** [thofma/Hecke.jl#45]
This is one example that triggers an "n1 not defined" error:
``
R,x = PolynomialRing(Hecke.ZZ,"x")
maximal_order(Hecke.NumberField(x^6+28153176769513638533819953494763742552095011029795886647010626985097770493447390786573312647386923245326294607649641017067997516829897062369182892772219258562789629151345178233470976*x^3+1087544917378569497489782414087715308104486063970662361708698298449681758488800617355980998085309157797376460545454402571140078116543476905649892273803228466894270759398058362231343906313018663670599695143861422721141563129150845697850601640755649472530205143222723244300807912375953120815029721479769822383312924719424335970141907758846596430457135098855468040192)[1])
``

I tried to naively change ``n1`` to ``na``, but then I get a division error up in the call stack.

**Comment by thofma** [comment]
Thanks for the report.

@CarloSircana

**Comment by CarloSircana** [comment]
Fixed.

**Comment by thofma** [comment]
Thanks Carlo!
