### ISSUE TITLE
Online manual for Hecke does not show which version it applies to

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#493]
The Hecke manuals at
- https://www.thofma.com/Hecke.jl/latest/
- https://www.thofma.com/Hecke.jl/stable/
- https://www.thofma.com/Hecke.jl/dev/
- http://www.thofma.com/Hecke.jl/v0.9.1/
- etc.

do not make it clear to which Hecke versions they apply (except of course those with an explicit version in the URL). Nor does there seem to be a way to switch to other versions, like one has on e.g. https://nemocas.github.io/Nemo.jl/dev/

The "Source" link for all of them seems to always point to the master branch, so that's not helpful either.

It would be good if the version was clearly visible. Perhaps MkDocs / the MkDocs integration in Documenter has an option for that?

**Comment by thofma** [comment]
Fixed by #501. We cannot add it to past docs, but now the dev version has it and so will the next release(s).
