### ISSUE TITLE
Possible bug in hnf

### ISSUE THREAD

**Issue by daviddelaat** [thofma/Hecke.jl#51]
I have a matrix where hnf seems to hang. Since it is quite large I have uploaded a serialized version here: www.daviddelaat.nl/mat.jls

The following hangs:
```julia 
using Serialization, Hecke
A = deserialize("mat.jls")
hnf(A)
```
The following code shows that hnf is very fast (less than a second) for the submatrix consisting of the first 350 rows, but then seems to hang indefinitely for the submatrix consisting of the first 351 rows. Row 351 doesn't seem particularly special to me (sparcity, bitsize).

```julia 
using Serialization, Hecke
A = deserialize("mat.jls")
B = sparse_matrix(FlintZZ)
for i = 1:nrows(A)
    @show i 
    push!(B, A[i])
    @time hnf(B, truncate=true)
end
```
Do you know what might be going on here?

BTW, in the code I see `@vprint` statements, how do I turn on this debugging output?

**Comment by fieker** [comment]
Hi David,

the problem has be found - but not quite fixed: we need to do more input
validation - in your matrix, row 61 is not sorted. Which causes the
algorithm to hang. In fact, many rows are not sorted.
How did you construct the matrix?

To you other question

set_verbose_level(:HNF, 1)

(or , 2) will switch the additional output on

even better

set_assert_level(:HNF, 1)

will crash your example at the infinite loop.

Greetings
 Claus

**Comment by daviddelaat** [comment]
Hello Claus,

Thanks for finding the problem so quickly! 

Sorting the entries fixes the problem indeed. We're generating the rows using the sparse_row function and a list of (index, value) pairs, where we didn't pay attention to the order at all. Perhaps instead of checking the order in hnf, the sparse_row function should always sort the input first?

Best,
David

**Comment by fieker** [comment]
On Tue, Nov 12, 2019 at 06:05:41AM -0800, David de Laat wrote:
> Hello Claus,
> 
> Thanks for finding the problem so quickly! 
> 
> Sorting the entries fixes the problem indeed. We're generating the
> rows using the sparse_row function and a list of (index, value) pairs,
> where we didn't pay attention to the order at all. Perhaps instead of
> checking the order in hnf, the sparse_row function should always sort
> the input first?
We're going to do that - although not always. Our use case produces
sorted arrays automatically, so the sorting would be too expensive
But clearly there need to be an option for it

Greetings
 Claus

**Comment by fieker** [comment]
sparse_row now has a keyword argument sort, defaulting to true

sparse_row(..., sort = false) 
assumes that the data is sorted

sparse_row(..., sort = true) which is equivalent to
sparse_row(....)

will sort 

Thanks and greetings
 Claus

**Comment by daviddelaat** [comment]
Thanks again! That's works perfectly!
