### ISSUE TITLE
Inconsistent behavior of `issquare(::fmpq)` and `issquare(::nf_elem)`

### ISSUE THREAD

**Issue by simonbrandhorst** [thofma/Hecke.jl#513]
For number fields `issquare` returns a tuple consisting of a boolean and a square root (if it exists)
For the rationals it just returns a boolean. 
```julia> F, a = number_field(x^2 +3)
(Number field over Rational Field with defining polynomial x^2 + 3, _a)

julia> issquare(a)
(false, 0)

julia> issquare(ZZ(4))
true

julia> issquare(QQ(4))
true
```
`issquare(::nf_elem)` should just return a bool.
If one wants  in addition the square root, then there is `issquare_with_sqrt`.

**Comment by thofma** [comment]
Yes, this is bad and needs to be fixed.

**Comment by thofma** [comment]
I think this is already fixed.
