### ISSUE TITLE
Functions not currently working

### ISSUE THREAD

**Issue by StevellM** [thofma/Hecke.jl#521]
I started to discover associative algebras `AlgAss` and their modules `ModAlgAss` today, and I have noticed that 3 functions were not currently working. I have found the bugs but I can't solve them by myself:

1. The first bug is in the functions `maximal_integral_ideal(O::AlgAssAbsOrd, p::Union{ fmpz, Int }, side::Symbol)` and `maximal_integral_ideal_containing(I::AlgAssAbsOrdIdl, p::Union{ fmpz, Int }, side::Symbol)` in the file ~[/src/AlgAssAbsOrd/Ideals.jl.](https://github.com/thofma/Hecke.jl/blob/master/src/AlgAssAbsOrd/Ideal.jl) There is the following block of lines 

```
1865 #P is the Jacobson radical of O/pO, so O/P is a simple algebra
1866  B, OtoB = quo(O, P, p)
1867  C, BtoC, CtoB = _as_algebra_over_center(B)
1868  D, CtoD = _as_matrix_algebra(C)
```

and the problem here is that the method `_as_algebra_over_center(bla)` has 2 arguments in output, not three. The remaining of the functions uses the 3 "objects" `C`, `BtoC` and `CtoB`. I have seen, while looking through the different commits modifying the same file, that the function `_islocally_free_left(O::AlgAssAbsOrd, I::AlgAssAbsOrdIdl, p::Union{Int, fmpz})` (line 1004) uses this method and have been modified to discard one of the 3 outputs.

2. The second bug is in the function `isirreducible(M::ModAlgAss)` of the file [~/src/ModAlgAss/ModAlgAss.jl.](https://github.com/thofma/Hecke.jl/blob/master/src/ModAlgAss/ModAlgAss.jl) At the lines 251-252, there are

```
251 If !(coefficient_ring(M) isa FiniteField)
252    error("Coefficient ring must be a finite field")
```

But the test in line 251 cannot compile. In fact, if I run this on my terminal

```
julia> F,z = FiniteField(5)
(Galois field with characteristic 5, 1)
 julia> F isa FiniteField
```

I got 

```
ERROR: TypeError: in isa, expected Type, got a value of type typeof(FlintFiniteField)
Stacktrace:
 [1] top-level scope
   @ REPL[27]:1
```

I guess the problem comes from the fact that on Oscar `FiniteField` is a constructor and not a type, or a structure, and so the `isa` doesn't behave as we want here. I haven't been able to find what to put in replacement of `FiniteField` here to make the test to compile.

**Comment by thofma** [comment]
Do you have reproducer for these issues? Just dump them here. That would be helpful.

**Comment by StevellM** [comment]
- For the first issue:
```
julia> K,z = cyclotomic_field(7);

julia> o = maximal_order(K);

julia> M = zeros(K,2,2,2);

julia> M[1,1,1] = one(K);

julia> M[1,2,2] = one(K);

julia> M[2,1,2] = one(K);

julia> M[2,2,1] = K(-12);

julia> E = Hecke.AlgAss(K,M)
Associative algebra of dimension 2 over Cyclotomic field of order 7

julia> OE = maximal_order(E);

julia> Hecke.maximal_integral_ideal(OE, 3*o, :left)
ERROR: BoundsError: attempt to access Tuple{AlgAss{fq}, Hecke.AlgAssExtMor{AlgAss{fq}, AlgAss{fq}, Hecke.AbsAlgAssToFqMor{AlgAss{fq}, FqFiniteField, fq_mat, FqPolyRing}, Vector{AlgAssElem{fq, AlgAss{fq}}}, Vector{fq}, fq_mat, Vector{AlgAssElem{fq, AlgAss{fq}}}}} at index [3]
Stacktrace:
 [1] indexed_iterate
   @ ./tuple.jl:86 [inlined]
 [2] maximal_integral_ideal(O::Hecke.AlgAssRelOrd{nf_elem, Hecke.NfAbsOrdFracIdl{AnticNumberField, nf_elem}, AlgAss{nf_elem}}, p::NfOrdIdl, side::Symbol)
   @ Hecke ~/.julia/packages/Hecke/M7nVW/src/AlgAssRelOrd/Ideal.jl:1299
 [3] top-level scope
   @ REPL[58]:1
```

- For the second, with the same `K` and `E` as before

```
julia> M = matrix(K, [[1,1],[1,2]]);

julia> N = matrix(K, [[1,0],[0,2]]);

julia> V = Hecke.Module(E,[M,N])
Module over field of dimension 2 (with algebra defined))

julia> Hecke.isirreducible(V)
ERROR: TypeError: in isa, expected Type, got a value of type typeof(FlintFiniteField)
Stacktrace:
 [1] isirreducible(M::Hecke.ModAlgAss{AnticNumberField, AbstractAlgebra.Generic.MatSpaceElem{nf_elem}, AlgAss{nf_elem}})
   @ Hecke ~/.julia/packages/Hecke/M7nVW/src/ModAlgAss/ModAlgAss.jl:251
 [2] top-level scope
   @ REPL[80]:1
```

**Comment by StevellM** [comment]
(Actually for the first I didn't mention the good file, but the same happens in both files)
