### ISSUE TITLE
Oscar warnings for Hecke

### ISSUE THREAD

**Issue by wbhart** [thofma/Hecke.jl#54]
In Oscar, I am seeing the following warnings when starting Oscar:

```
WARNING: eval from module Hecke to Oscar:    
Expr(:global, Expr(:call, :signature, Expr(:::, :K, :AnticNumberField)) = Expr(:block, #= Symbol("/home/travis/.julia/packages/Hecke/UZrlo/src/Hecke.jl"):238 =#, Expr(:call, :_signature, :K)))
  ** incremental compilation may be broken for this module **
WARNING: Method definition signature(Nemo.AnticNumberField) in module Nemo at /home/travis/.julia/packages/Nemo/5aSWJ/src/antic/nf_elem.jl:245 overwritten in module Hecke at /home/travis/.julia/packages/Hecke/UZrlo/src/Hecke.jl:238.
```

**Comment by wbhart** [comment]
There is also still this:

```
WARNING: could not import Nemo.set_entry! into Hecke
```

**Comment by thofma** [comment]
Computing the signature of a number field turned out to be a bottleneck, so we overwrite the Nemo method with a method the caches the result.

One option would be to just move this method over.

**Comment by wbhart** [comment]
We could add a signature field to the number field structure and initially set it to 0,0. Then the signature function could look it up first. Would that be suitable.

We have to be a little careful with the precedent we set. Just about any function could be a bottleneck in someone's calculation, and I don't think we want the library littered with cached functions. But given that this is a standard property of a parent object whose value can't change, I think a fair case can be made here.

**Comment by thofma** [comment]
I can do that.

Another option would be to just remove the function from Nemo. It is not a function which exists in antic.

**Comment by wbhart** [comment]
Yes, in some ways that is a nicer solution. It is breaking. But if you are also taking care of the upstream problems in Hecke for that, then it should be ok.

**Comment by thofma** [comment]
Breaking means we would need Nemo version 0.16.2 or 0.17.0?

**Comment by wbhart** [comment]
I guess it would have to be 0.17.0 technically, as we remove an interface function.

By the way, I will release Oscar 0.0.1 tomorrow at 5pm. I can switch everything to use 0.17.0 by then if Hecke is also supporting that version. Otherwise I will use 0.16.0 in Hecke, which will mean Oscar will have the ugly warning. I don't mind which. It isn't the most important Oscar release we will ever have. But it might be useful information. I understand you won't be in, so no pressure.

**Comment by thofma** [comment]
I have just tagged a new Hecke release (0.7.1), where I disabled the warnings temporarily so that we will have a warning free Oscar.

P.S.: The warning `could not import Nemo.set_entry! into Hecke` is actual a bug in Nemo. This is symbol is exported but there is no function with this name.

**Comment by wbhart** [comment]
Ah, right. I removed the function and did not remove the export. I'll do that in a PR now (no need to issue a new release just for that).

**Comment by thofma** [comment]
I worked around it for now. The latest Hecke release won't give any warnings.

**Comment by wbhart** [comment]
Sure. Thanks.
