### ISSUE TITLE
Relative residue field vs. residue field of relative extensions

### ISSUE THREAD

**Issue by StevellM** [thofma/Hecke.jl#639]
As far as I see, if we are given a relative extension of number fields, creating the residue field of the top field will create a field not over the residue field of the bottom field, but over some regular finite field. For instance:
```
julia> Qx, x = QQ["x"]
(Univariate Polynomial Ring in x over Rational Field, x)

julia> Qx, x = QQ["x"];

julia> K,a = number_field(x^4+x+1, "a");

julia> Kt, t = K["t"];

julia> E, b = number_field(t^2-a*t+1,"b");

julia> OK = maximal_order(K);

julia> OE = maximal_order(E);

julia> p = prime_decomposition(OK, 11)[1][1];

julia> P = prime_decomposition(OE,p)[1][1];

julia> FE, _ = ResidueField(OE, P);

julia> FK, _ = ResidueField(OK, p);

julia> FE
Finite field of degree 6 over F_11

julia> FK
Finite field of degree 3 over F_11

julia> defining_polynomial(FE)
x^6 + 3*x^4 + 4*x^3 + 6*x^2 + 7*x + 2
```
It would be interesting to have the version as a `RelFiniteField` since the type exists and has some functionalities. However, it doesn't seem to be used. I guess I have an idea on how to produce it, but I only know the defining polynomial if `p` is not an index divisor in `OE` : 

```
julia> isindex_divisor(OE, p)
false

julia> P.non_index_div_poly
y^2 + 10*$*y + 1
```
but in the general case I don't see how to produce it. The goal would be to use this in order to provide completion of an arbitrary tower of extensions of number fields (and thus this will be needed to create the unramified parts at every step).

**Comment by thofma** [comment]
Hm, I thought Carlo used this in one form or the other for the local fields.

@joschmitt did you ever need the relative extensions of the residue fields for the algebras?

**Comment by thofma** [comment]
P.S.: The easiest way that always works is just computing the embedding `FK -> FE` (via the maps named `_`) and compute the relative extension from there.

**Comment by joschmitt** [comment]
> @joschmitt did you ever need the relative extensions of the residue fields for the algebras?

I'm not sure I understand the question. I don't think there was `RelFiniteField` "back then". I probably did the stuff in `Map/FqPolyRing.jl` which is an earlier (?) version of the relative extensions.
The code that's used for the quotients in the relative number fields should mainly be in `Map/NfRelOrd.jl`.

**Comment by StevellM** [comment]
Ok great, thanks for the information! I will make the code(s) similarly to what have been already done.
