### ISSUE TITLE
Argument order in `factor` unintuitive

### ISSUE THREAD

**Issue by mgkurtz** [thofma/Hecke.jl#641]
Factorizing rationals is done via `factor(QQ(3, 4), ZZ)`, but I would expect `factor(ZZ, QQ(3, 4))` instead. The latter would be as in other Oscar functions, where we first give the ring and then elements. Point 4 in the [argument order according to the Julia style guide](https://docs.julialang.org/en/v1/manual/style-guide/#Write-functions-with-argument-ordering-similar-to-Julia-Base) also hints us, that the ring (which determines the output type) should come first.

The same applies to other `factor` methods.

**Comment by lgoettgens** [comment]
This will be resolved by https://github.com/thofma/Hecke.jl/pull/1094, https://github.com/Nemocas/AbstractAlgebra.jl/pull/1374, and https://github.com/oscar-system/Oscar.jl/pull/2433.
