### ISSUE TITLE
Problem with `iseven` and `ZGenus`

### ISSUE THREAD

**Issue by StevellM** [thofma/Hecke.jl#664]
```
julia> G = genera((3,19), 1, even = true)[1]
ZGenus
Signature: (3, 19)
Genus symbol at 2:   1^22

julia> iseven(G)
false
```

Is don't know whether the function `iseven` is bugged or the construction of the local genus at `2` is, but this seems wrong. Though, it gets back to normal if I look for a representative:

```
julia> L = representative(G)
Quadratic lattice of rank 22 and degree 22 over the rationals

julia> iseven(L)
true
```

**Comment by thofma** [comment]
Can you check with Magma/Sage?

**Comment by StevellM** [comment]
Magma for sure I can't, Sage I might be able to do it yes.

**Comment by simonbrandhorst** [comment]
> ```
> julia> G = genera((3,19), 1, even = true)[1]
> ZGenus
> Signature: (3, 19)
> Genus symbol at 2:   1^22
> 
> julia> iseven(G)
> false
> ```
> 
> Is don't know whether the function `iseven` is bugged or the construction of the local genus at `2` is, but this seems wrong. Though, it gets back to normal if I look for a representative:
> 
> ```
> julia> L = representative(G)
> Quadratic lattice of rank 22 and degree 22 over the rationals
> 
> julia> iseven(L)
> true
> ```

That is certainly a bug.

**Comment by simonbrandhorst** [comment]
It is even.
