### ISSUE TITLE
`is_infinite` vs. generality and vs. `isinf`

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#705]
Hecke adds a new function `is_infinite`, for `EllCrvPt`, `Hecke.LocalField`, and `GrpAbFinGen`.

1. Should this perhaps instead have one generic default method, `is_infinite(x) = !is_finite(x)` ?
2. If so, is there even a point in having this in addition to `is_finite` ?
3. How does this relate to `isinf` aka `is_inf`? There is an argument to say these should be distinct, except...
4. Hecke also has a singleton type `PosInf` for which `is_finite` is implemented, but neither `isinf` and `is_infinite`, though arguable both would make sense for it?

Of course there is a clash between 1 and 3: if we make `is_infinite` and alias for `isinf` then we can't really add a generic fallback method, as that would be type piracy, wouldn't it?

CC: @thofma @fieker

**Comment by fingolfin** [comment]
I guess `isinf` only has a very few methods, so of course we could also do `is_infinite` methods that redirect to it for just those cases (probably for `Number`?)

**Comment by thofma** [comment]
1) Yes, I guess we could have a default fallback of this form. 
2) I often like to avoid double negative `!is_infinite`.
3) Not sure.
4) Yes.

And yes to the clash.

Here is my proposal (numbering unrelated to your list):
1. Add the `is_infinite(x) = !is_finite(x)` fallback.
2. Change everything to implement `is_finite` (including `PosInf`).
3. Add the `isinf` for `PosInf` so that it feels more like a `Number` (whatever this is supposed to be). 

What do you think @fingolfin?

**Comment by fingolfin** [comment]
Sounds good to me. The docstring for `is_infinite` should probably also point out that no methods should be installed normally, instead one should install a method for `is_finite` (aka `Base.isfinite`...)

**Comment by fingolfin** [comment]
I looked into addressing this in a PR, and then started to wonder... if `PosInf` meant to be an infinite value for the integers (as would be suggested by the fact that its arithmetic and comparison operations are mostly only implemented for `Int` arguments); or also for Rational{Int} (one method there); or should it be possible to also compare it against any `Real` and even `fmpz` and `fmpq` (it wouldn't be hard to cover all those, but it's not clear to me whether this is desirable at this point).

For now I am going to stick with the assumption that it is for `Int`.

**Comment by thofma** [comment]
I implemented the smallest number of methods to make it useful for us back then. I would stick to `Int` as you did for now.
