### ISSUE TITLE
Error loading Hecke when it is only installed "indirectly"

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#75]
This line (only executed in Julia <= 1.3) is problematic; it results in an exception when Hecke is not installed directly, but only indirectly as a dependency.
https://github.com/thofma/Hecke.jl/blob/f628073be87b8111fc356b595f2bc0e10c150ffd/src/Hecke.jl#L414

This leads to CI failures on Travis for Oscar.jl, see https://travis-ci.com/github/oscar-system/Oscar.jl/jobs/352656108

I am working on a workaround for the above issue, but it would be nice if this was also fixed in Hecke (and other packages using similar code).

**Comment by thofma** [comment]
I remember sawing this once and reporting it to Claus.

**Comment by fieker** [comment]
On Tue, Jun 23, 2020 at 09:13:08AM -0700, thofma wrote:
> I remember sawing this once and reporting it to Claus.

It was "fixed" for Nemo, but not for Hecke. Done now
