### ISSUE TITLE
Citing Hecke

### ISSUE THREAD

**Issue by StevellM** [thofma/Hecke.jl#775]
According to the main page of the GitHub for Hecke, we should cite Hecke as back in 2017. I guess things changed a lot since then, and in particular citing Hecke regarding the last stable release version used for our computations seem more appropriate (to me).

Is there any other template for this or should we stick to the one provided in the main page ?

**Comment by thofma** [comment]
We would appreciate if you cite the article from 2017, where Hecke has been announced. Additional information on the specific version could be mentioned in the text.

**Comment by thofma** [comment]
I will close this for now. Please reopen if there is some remaining question.
