### ISSUE TITLE
Enhancement: Idempotents for group algebras

### ISSUE THREAD

**Issue by joschmitt** [thofma/Hecke.jl#784]
Maybe I'm missing something, but I find it unnecessarily complicated to compute idempotents of a group algebra `KG` (finite group, characteristic zero). I either have to do `decompose` and map the ones back by hand or `Hecke._primitive_idempotents(AlgAss(KG)[1])` and then map the result back from `AlgAss(KG)` to `KG`.

**Comment by thofma** [comment]
Yes, I did this quite often recently. Do you mean central primitive idempotents?

**Comment by joschmitt** [comment]
Yes, sorry, central primitive idempotents.
