### ISSUE TITLE
problem with fmpz_mat

### ISSUE THREAD

**Issue by ThomasBreuer** [thofma/Hecke.jl#82]
(I am not sure whether this is an issue for Nemo or for Hecke.)
Currently the following happens.
```
julia> using Hecke
[...]

julia> A = fmpz_mat([1 0 ; 0 1]);

julia> b = fmpz_mat(2, 1, [1, 0]);

julia> Hecke.solve(A, b)
ERROR: UndefRefError: access to undefined reference
[...]
```
The point is that `b` does not have the field `base_ring` (which is available in `A`).
The matrix `A` gets created by a method from Hecke, whereas the method for creating `b` belongs to Nemo.
Perhaps the Hecke methods set the field `base_ring` and rely on it, but the Nemo methods do not know this?
When one creates `b` as `fmpz_mat([1 0])'` then one gets an object of the same type as before, but the field is available, and `Hecke.solve` works.

**Comment by thofma** [comment]
Hi Thomas! The proper way to construct matrices over a ring `R` is `matrix(R, ...)`, so in the first case would be `matrix(FlintZZ, [1 0; 0 1])`. This documented here: http://nemocas.github.io/Nemo.jl/latest/matrix.html.

**Comment by fieker** [comment]
On Wed, Sep 02, 2020 at 03:48:14PM +0000, ThomasBreuer wrote:
> (I am not sure whether this is an issue for Nemo or for Hecke.)
> Currently the following happens.
> ```
> julia> using Hecke
> [...]
> 
> julia> A = fmpz_mat([1 0 ; 0 1]);
> 
> julia> b = fmpz_mat(2, 1, [1, 0]);
> 
> julia> Hecke.solve(A, b)
> ERROR: UndefRefError: access to undefined reference
> [...]
> ```
> The point is that `b` does not have the field `base_ring` (which is available in `A`).
> The matrix `A` gets created by a method from Hecke, whereas the method for creating `b` belongs to Nemo.
> Perhaps the Hecke methods set the field `base_ring` and rely on it, but the Nemo methods do not know this?
> When one creates `b` as `fmpz_mat([1 0])'` then one gets an object of the same type as before, but the field is available, and `Hecke.solve` works.
> 
Essentially, you're not supposed to use fmpz_mat directly. The parent in
A is not supposed to be there.
The "proper" way is to use
matrix(ZZ, 2, 1, ....)
