### ISSUE TITLE
Issue with relative norms and factored elements

### ISSUE THREAD

**Issue by wyoumansUSF** [thofma/Hecke.jl#83]
Let L be a subfield of K, m an injection of L into K, and x a factored element in K. Then `x*x^-1` is a factored element with an empty dictionary. The relative norm `norm(m, x*x^-1)` throws `ERROR: Dictionary must not be empty` (but `norm(x*x^-1) = 1` as expected).

**Comment by thofma** [comment]
Thanks. I will fix it tomorrow. If you need a fix now, there is method of the `FacElem` constructor, which takes as the first argument the base field. (We have not adjusted all call sites yet.)

**Comment by wyoumansUSF** [comment]
Thanks! That's ok it was an easy workaround, just letting you know.
