### ISSUE TITLE
Migrating from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#85]
In 2018, Travis CI decided to merge travis-ci.org (for open source projects) into travis-ci.com (previously only for commercial projects). This migration has been possible already for some time as a "beta feature". But now there is a deadline: December 31, 2020, they will shutdown travis-ci.org. So projects using travis-ci.org are well advised to migrate before that at a convenient time, to avoid hassle. I've done this several times for multiple projects and can try to provide some assistance.

Details can be found [in this email](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D) and [here you can find migration instructions](https://docs.travis-ci.com/user/migrate/open-source-repository-migration). In my experience, migration is really easy and smooth, but YMMV.

Oh and of course afterwards, URLs in e.g. the README.md (for status badges) and on external websites etc. need to be adjusted.

**Comment by thofma** [comment]
Fixed.
