### ISSUE TITLE
Document `@req`

### ISSUE THREAD

**Issue by fingolfin** [thofma/Hecke.jl#919]
In https://github.com/oscar-system/Oscar.jl/pull/1811 I saw code using `@req` and wondered what it does. Had to grep around a bit. Would have been nice if `?@req` had cleared it up :-). Perhaps we can document it and then use it in more places?

**Comment by thofma** [comment]
Without any bias I fully support this proposal.

**Comment by thofma** [comment]
Fixed by #984
